version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build complete. Syncing to S3..."
      - aws s3 sync dist/ s3://this-is-devops-bucket --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
